master-smgoro:
  push:
    - name: update-latest-tag
      stages:
        - name: move-latest-tag-to-head
          script: |
            set -eu

            CURRENT_COMMIT=$(git rev-list -n 1 latest 2>/dev/null || true)
            if [ "$CURRENT_COMMIT" = "$CNB_COMMIT" ]; then
              echo "latest already points to $CNB_COMMIT"
              exit 0
            fi

            git config user.name "cnb"
            git config user.email "cnb@local"

            git tag -fa latest -m "latest -> $CNB_COMMIT"
            git push origin refs/tags/latest --force

"$":
  tag_push:
    - name: release-build
      docker:
        image: node:20-bullseye
        volumes:
          - /root/.npm
      stages:
        - name: verify-tag-from-master-smgoro
          script: |
            set -eu
            git fetch origin master-smgoro:refs/remotes/origin/master-smgoro
            TAG_COMMIT=$(git rev-list -n 1 "$CNB_BRANCH")

            if ! git merge-base --is-ancestor "$TAG_COMMIT" "origin/master-smgoro"; then
              echo "Tag commit $TAG_COMMIT is not on branch master-smgoro history"
              exit 1
            fi

        - name: prepare-tools
          script: |
            set -eu
            apt-get update
            apt-get install -y wget zip tar

        - name: build-project
          script: |
            set -eu
            chmod a+x ./install-dependents.sh ./build.sh
            ./install-dependents.sh
            ./build.sh

        - name: add-binaries
          script: |
            set -eu
            wget --input-file=lib-urls.txt --directory-prefix=production-code/daemon/lib/

        - name: package-artifacts
          script: |
            set -eu

            cp -r production-code dist_linux
            mv production-code dist_windows

            cp prod-scripts/linux/* dist_linux/
            cp prod-scripts/windows/* dist_windows/

            cp LICENSE dist_linux/LICENSE
            cp LICENSE dist_windows/LICENSE

            wget https://nodejs.org/download/release/latest-v20.x/win-x64/node.exe -O dist_windows/daemon/node_app.exe
            cp dist_windows/daemon/node_app.exe dist_windows/web/node_app.exe

            mv dist_linux/ mcsmanager/
            tar czf mcsmanager_linux_release.tar.gz mcsmanager/
            tar --exclude='mcsmanager/daemon' --exclude='mcsmanager/start-daemon.sh' -czf mcsmanager_linux_web_only_release.tar.gz mcsmanager/
            tar --exclude='mcsmanager/web' --exclude='mcsmanager/start-web.sh' -czf mcsmanager_linux_daemon_only_release.tar.gz mcsmanager/
            rm -rf mcsmanager/

            mv dist_windows/ mcsmanager/
            zip -r mcsmanager_windows_release.zip mcsmanager/
            zip -r mcsmanager_windows_web_only_release.zip mcsmanager/ -x "mcsmanager/daemon/*"
            zip -r mcsmanager_windows_daemon_only_release.zip mcsmanager/ -x "mcsmanager/web/*"

        - name: create-cnb-release
          type: git:release
          options:
            title: $CNB_BRANCH
            overlying: true

        - name: upload-cnb-release-assets
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - ./mcsmanager_windows_release.zip
              - ./mcsmanager_windows_web_only_release.zip
              - ./mcsmanager_windows_daemon_only_release.zip
              - ./mcsmanager_linux_release.tar.gz
              - ./mcsmanager_linux_web_only_release.tar.gz
              - ./mcsmanager_linux_daemon_only_release.tar.gz
